---
- name: Install and Configure Docker
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      tags:
        - docker

    - name: Install curl and jq
      apt:
       name: "{{ packages }}"
       state: present
      vars:
        packages:
          - curl
          - jq
      tags:
        - docker

    - name: Enable container logging to syslog # https://docs.docker.com/config/containers/logging/syslog/
      copy:
        content: |
          {
            "log-driver": "syslog",
            "log-opts": {
              "syslog-address": "udp://localhost:514"
            }
          }
        dest: /etc/docker/daemon.json
      notify: Restart Docker
      tags:
        - docker

  handlers:
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
